import { environment } from "environments/environment";

export const apiurls = {
  createUser: `${environment.userApiUrl}users/create`,
  getUsers: `${environment.userApiUrl}users?division_id`,
  getRole: `${environment.userApiUrl}mdm/roles?division_id`,
  getDivision: `${environment.userApiUrl}mdm/divisions`,
  getDistrictByStateId: `${environment.userApiUrl}mdm/districts/`,
  getState: `${environment.userApiUrl}mdm/states?division_id`,
  geDistrictByState: `${environment.userApiUrl}api/districts/`,
  updateUserById: `${environment.userApiUrl}users/update-user/`,
  getDesignations: `${environment.userApiUrl}mdm/designations`,
  userLogin: `${environment.userApiUrl}users/login`,
  getUnitsByDistictId: `${environment.userApiUrl}mdm/units/`,
  // uploadInfo: `${environment.userApiUrl}casedata/save`,
  saveDraft: `${environment.userApiUrl}casedata/saveDraft`,
  caseDataSubmit: `${environment.userApiUrl}casedata/submit`,
  getCaseDataDrafts: `${environment.userApiUrl}casedata/drafts`,
  getUploadInfo: `${environment.userApiUrl}casedata/search`,
  filePreview: `${environment.userApiUrl}casedata/filePreview`,
  getFavourites: `${environment.userApiUrl}casedata/favourites?division_id`,
  getFilesLatest: `${environment.userApiUrl}casedata/files/latest`,
  casedataUpdate: `${environment.userApiUrl}casedata/update/`,
  favourite: `${environment.userApiUrl}casedata/files`,
  getRolesMatser: `${environment.userApiUrl}mdm/roles?division_id`,
  getDivisionsMaster: `${environment.userApiUrl}mdm/divisions?division_id`,
  getDesignationsMaster: `${environment.userApiUrl}mdm/designations?division_id`,
  saveRole: `${environment.userApiUrl}mdm/roles`,
  saveDesignations: `${environment.userApiUrl}mdm/designations`,
  saveDivision: `${environment.userApiUrl}mdm/divisions`,
  getCurrentUser: `${environment.userApiUrl}users/currentUsers`,
  getNotifications: `${environment.userApiUrl}casedata/notifications?division_id`,
  approveFiles: `${environment.userApiUrl}casedata/approve-file`,
  getContentManagerReq: `${environment.userApiUrl}casedata/requests`,
  getFileTypes: `${environment.userApiUrl}mdm/fileTypes`,
  getFileClassification: `${environment.userApiUrl}mdm/fileClassification`,
  getDomain: `${environment.userApiUrl}mdm/domain`,
  getDomainNames: `${environment.userApiUrl}mdm/domain/names`,
  getCaseStatus: `${environment.userApiUrl}mdm/caseStatus`,
  getCmoradmins: `${environment.userApiUrl}users/getcmoradmins`,
  caseDataFilePreview: `${environment.userApiUrl}casedata/filePreview`,
  caseDataFileApproveReq: `${environment.userApiUrl}casedata/access`,
  casedataRevoke: `${environment.userApiUrl}casedata/revoke`,
  markasreadNotification: `${environment.userApiUrl}casedata/markasread`,
  getMasterDropDown: `${environment.userApiUrl}mdm/lookup`,
  casedataUploadApprovals: `${environment.userApiUrl}casedata/upload-approvals`,
  departmentsAddUpdateDelete: `${environment.userApiUrl}mdm/departments`,
  designationsHierachyAdd: `${environment.userApiUrl}mdm/designation-hierarchy`,
  uploadApprovalsByID: `${environment.userApiUrl}casedata/upload-approvals`,
  caseFiles: `${environment.userApiUrl}mdm/caseFiles`,
  correspondenceFiles: `${environment.userApiUrl}mdm/correspondenceFiles`,
  manageSMTP:`${environment.userApiUrl}mdm/smtp`,
  designationsFilterByDepartmentId: `${environment.userApiUrl}mdm/designations?departmentId`,
  divisionsFilterByDepartmentId: `${environment.userApiUrl}mdm/divisions?departmentId`,
  designationsFilterByDivisionId: `${environment.userApiUrl}mdm/designations?divisionId`,
  updateFileDataById: `${environment.userApiUrl}casedata/updateFileData`,
  searchUsers: `${environment.userApiUrl}users/search-users`,
  updateCaseDetailsById: `${environment.userApiUrl}casedata`,
  setPassword: `${environment.userApiUrl}users/set-password`,
  forgotPassword: `${environment.userApiUrl}users/request-otp`,
  verifyOtp: `${environment.userApiUrl}users/verify-otp`,
  resetPassword: `${environment.userApiUrl}users/reset-password`,
  requestAdminReset: `${environment.userApiUrl}users/reset-pwd-request`,
  adminSetDefaultPwd: `${environment.userApiUrl}users/set-default-pwd/`,
  getallRequests: `${environment.userApiUrl}users/getallRequests`,
  userSetPassword: `${environment.userApiUrl}users/set-password/`,
  setStatusPasswordReset: `${environment.userApiUrl}users/setStatus`,
  folderTree: `${environment.userApiUrl}cm/folder-tree`,
  moveFiles: `${environment.userApiUrl}cm/move-files`,
  archiveFiles : `${environment.userApiUrl}cm/archive-files`,
  getUsersData : `${environment.userApiUrl}users/get-user-data/`,
  sendPwdReset : `${environment.userApiUrl}users/send-pwd-reset/`,
  folderTreeView : `${environment.userApiUrl}cm/folder-tree-view`,
  archiveFolderTreeView : `${environment.userApiUrl}cm/archive`,
  unarchiveFolderTreeView : `${environment.userApiUrl}cm/unarchive`,
  copyFiles : `${environment.userApiUrl}cm/copy-files`,
  mergeFolders : `${environment.userApiUrl}cm/merge`,
  sendReminder: (id: number | string) =>
    `${environment.userApiUrl}casedata/requests/${id}/send-reminder`,
  withdrawRequest: (id: number | string) =>
    `${environment.userApiUrl}casedata/withdraw-access-requests/${id}`,
  sendReminderPendingApproval: (id: number | string) =>
    `${environment.userApiUrl}casedata/upload-approval/${id}/send-reminder`,
  withdrawPendingApproval: (id: number | string) =>
    `${environment.userApiUrl}casedata/withdraw-upload-approval/${id}`,
  checkEmailExists: `${environment.userApiUrl}users/check-email-exists`,
} as const;
