import { environment } from "environments/environment";

export const apiurls = {
  createUser: `${environment.userApiUrl}users/create`,  
  getUsers: `${environment.userApiUrl}users?division_id`,  
  getRole: `${environment.userApiUrl}mdm/roles?division_id`,  
  getDivision: `${environment.userApiUrl}mdm/divisions`,
  getDistrictByStateId: `${environment.userApiUrl}mdm/districts/`,
  getState: `${environment.userApiUrl}mdm/states?division_id`,
  geDistrictByState: `${environment.userApiUrl}api/districts/`,
  updateRoleByRoleId: `${environment.userApiUrl}users/update-user/`,
  getDesignations: `${environment.userApiUrl}mdm/designations`,
  userLogin: `${environment.userApiUrl}users/login`,
  getUnitsByDistictId :`${environment.userApiUrl}mdm/units/`,
   uploadInfo :`${environment.userApiUrl}casedata/save`,
   getUploadInfo :`${environment.userApiUrl}casedata/search`,
   filePreview :`${environment.userApiUrl}casedata/filePreview`,
   getFavourites :`${environment.userApiUrl}casedata/favourites?division_id`,
   getFilesLatest :`${environment.userApiUrl}casedata/files/latest`,
   casedataUpdate :`${environment.userApiUrl}casedata/update/`,
   favourite :`${environment.userApiUrl}casedata/files`,
   getRolesMatser :`${environment.userApiUrl}mdm/roles?division_id`,
   getDivisionsMaster :`${environment.userApiUrl}mdm/divisions?division_id`,
   getDesignationsMaster:`${environment.userApiUrl}mdm/designations?division_id`,
   saveRole:`${environment.userApiUrl}mdm/roles`,
   saveDesignations:`${environment.userApiUrl}mdm/designations`,
   saveDivision:`${environment.userApiUrl}mdm/divisions`,
   getCurrentUser:`${environment.userApiUrl}users/currentUsers`,
   getNotifications :`${environment.userApiUrl}casedata/notifications?division_id`,
   approveFiles :`${environment.userApiUrl}casedata/approve-file`,
   getContentManagerReq :`${environment.userApiUrl}casedata/requests`,
   getFileTypes:`${environment.userApiUrl}mdm/fileTypes`,
   getFileClassification:`${environment.userApiUrl}mdm/fileClassification`,
   getCaseStatus:`${environment.userApiUrl}mdm/caseStatus`,
   getCmoradmins:`${environment.userApiUrl}users/getcmoradmins`,
   caseDataFilePreview :`${environment.userApiUrl}casedata/filePreview`,
   caseDataFileApproveReq :`${environment.userApiUrl}casedata/access`,
   casedataRevoke :`${environment.userApiUrl}casedata/revoke`,
   markasreadNotification :`${environment.userApiUrl}casedata/markasread`,
   getMasterDropDown: `${environment.userApiUrl}mdm/lookup`,
   casedataUploadApprovals :`${environment.userApiUrl}casedata/upload-approvals`,
   departmentsAddUpdateDelete:`${environment.userApiUrl}mdm/departments`,
   designationsHierachyAdd:`${environment.userApiUrl}mdm/designation-hierarchy`,
    uploadApprovalsByID:`${environment.userApiUrl}casedata/upload-approvals`,
}as const;
